apiVersion: security.vinz.in/v1alpha1
kind: VulnImage
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: vulnimage-sample
spec:
  image: nginx
